version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
      - ./data:/app/data  # For SQLite database
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DATABASE_URL=sqlite:///./data/assistant.db
      - ENVIRONMENT=production
      - DEBUG=False
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:8000
      - USER_ID=${USER_ID:-default_user}
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  data:  # For persistent SQLite database storage