version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # Backend API
      - "8501:8501"  # Frontend Streamlit
    volumes:
      - ./data:/app/data  # Persist SQLite database
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - USER_ID=${USER_ID:-default_user}
      - DATABASE_URL=sqlite:///./data/chat.db
      - ENVIRONMENT=development
      - DEBUG=True
      - PORT=8000
      - BACKEND_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3 