services:
  - type: web
    name: ai-assistant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd /opt/render/project/src && PYTHONPATH=/opt/render/project/src uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: USER_ID
        value: default_user
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.10.0"
    healthCheckPath: /api/health
    autoDeploy: true 